# Generated by Django 5.1.11 on 2025-08-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SeoulBikeHourly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("hour", models.PositiveSmallIntegerField()),
                ("rented_bike_count", models.IntegerField()),
                ("temperature_c", models.FloatField()),
                ("humidity_pct", models.FloatField()),
                ("windspeed_ms", models.FloatField()),
                ("visibility_10m", models.FloatField()),
                ("dew_point_c", models.FloatField()),
                ("solar_radiation_mj_m2", models.FloatField()),
                ("rainfall_mm", models.FloatField()),
                ("snowfall_cm", models.FloatField()),
                ("seasons", models.CharField(max_length=16)),
                ("holiday", models.CharField(max_length=8)),
                ("functioning_day", models.CharField(max_length=8)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date"], name="analytics_s_date_a7e238_idx"),
                    models.Index(fields=["hour"], name="analytics_s_hour_e997e8_idx"),
                    models.Index(
                        fields=["seasons"], name="analytics_s_seasons_a25c59_idx"
                    ),
                    models.Index(
                        fields=["functioning_day"],
                        name="analytics_s_functio_5a1184_idx",
                    ),
                ],
                "unique_together": {("date", "hour")},
            },
        ),
    ]
